var ans = [];
var sum = 0;

for (var i = 1; i < 1000; i++) {
    if (i % 3 === 0 || i % 5 === 0) {
        ans.push(i);
        sum += i;
    }
}

/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

var fib = [1,2];
var result = 0;

for (i = 2; i < 4000000; i++) {
    if (fib[i-1] < 4000000) {
      fib[i] = fib[i - 1] + fib[i - 2];
    }
}

for (j = 0; j < fib.length; j++) {
    if(fib[j] % 2 == 0){
        result = result + fib[j];
    }
}
